// <auto-generated />
using System;
using Desafio.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Desafio.Infrastructure.Migrations
{
    [DbContext(typeof(DesafioDbContext))]
    partial class DesafioDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Desafio.Infrastructure.Data.Models.DividaData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CPF")
                        .HasColumnType("text");

                    b.Property<string>("NomeDevedor")
                        .HasColumnType("text");

                    b.Property<int>("NumeroTitulo")
                        .HasColumnType("integer");

                    b.Property<decimal>("PorcentagemJuros")
                        .HasColumnType("numeric");

                    b.Property<decimal>("PorcentagemMulta")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.ToTable("Dividas");
                });

            modelBuilder.Entity("Desafio.Infrastructure.Data.Models.ParcelaData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataVencimento")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("DividaDataId")
                        .HasColumnType("integer");

                    b.Property<int>("NumeroParcela")
                        .HasColumnType("integer");

                    b.Property<decimal>("ValorParcela")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("DividaDataId");

                    b.ToTable("Parcelas");
                });

            modelBuilder.Entity("Desafio.Infrastructure.Data.Models.ParcelaData", b =>
                {
                    b.HasOne("Desafio.Infrastructure.Data.Models.DividaData", null)
                        .WithMany("Parcelas")
                        .HasForeignKey("DividaDataId");
                });

            modelBuilder.Entity("Desafio.Infrastructure.Data.Models.DividaData", b =>
                {
                    b.Navigation("Parcelas");
                });
#pragma warning restore 612, 618
        }
    }
}
